Attire.delete_all
RendezvousType.delete_all


Attire.create(name: "Formal")
Attire.create(name: "Semi-Formal")
Attire.create(name: "Swimwear")
Attire.create(name: "Outdoor Clothes")
Attire.create(name: "Something Comfortable")
Attire.create(name: "Running/Exercise Clothes")
Attire.create(name: "Overnight Clothes")
Attire.create(name: "Multiple Outfits")
Attire.create(name: "Casual")
Attire.create(name: "Something Attractive")
Attire.create(name: "Cosplay")



RendezvousType.create(name: "Take a Walk")
RendezvousType.create(name: "Go on a Picnic")
RendezvousType.create(name: "Eat at a new Restraunt")
RendezvousType.create(name: "Go to a Coffee Shop")
RendezvousType.create(name: "PLay Board Games")
RendezvousType.create(name: "Go to a Movie")
RendezvousType.create(name: "Go to Arcade")
RendezvousType.create(name: "Go Bowling")
RendezvousType.create(name: "Play Mini-Golf")
RendezvousType.create(name: "Go on a Scavenger Hunt")
RendezvousType.create(name: "Go to a Museum")
RendezvousType.create(name: "Take a Scenic Drive")
RendezvousType.create(name: "Go to a Park")
RendezvousType.create(name: "Volunteer Together")
RendezvousType.create(name: "Play Laser Tag")
RendezvousType.create(name: "Go to a Painting Class")
RendezvousType.create(name: "Go Go-Kart Racing")
RendezvousType.create(name: "Go Hiking")
RendezvousType.create(name: "Double Date")
RendezvousType.create(name: "Cook a Meal Together")
RendezvousType.create(name: "Go Stargazing")
RendezvousType.create(name: "Date Night In")
RendezvousType.create(name: "Get Ice Cream")
RendezvousType.create(name: "Go Roller Skating")
RendezvousType.create(name: "Take a Pottery Class")
RendezvousType.create(name: "Visit Family")
RendezvousType.create(name: "DIY Project Together")
RendezvousType.create(name: "Go to a Concert")
RendezvousType.create(name: "Play Basketball")
RendezvousType.create(name: "Go Swimming")
RendezvousType.create(name: "Go to a Lake")
RendezvousType.create(name: "Have a Campfire")
RendezvousType.create(name: "Go see a National Monument")
RendezvousType.create(name: "Play Volleyball")
RendezvousType.create(name: "Go to the Batting Cages")
RendezvousType.create(name: "Write Poems Together")
RendezvousType.create(name: "Go to a Plant Nusery")
RendezvousType.create(name: "Go to a Animal Shelter")
RendezvousType.create(name: "Go to a Trampoline Park")
RendezvousType.create(name: "Go to the Library")
RendezvousType.create(name: "Go Thrift Store Shopping")
RendezvousType.create(name: "Play Frisbee Golf")
RendezvousType.create(name: "See a Comedy Show")
RendezvousType.create(name: "Build-a-Bear")
RendezvousType.create(name: "Go get Frozen Yogurt")
RendezvousType.create(name: "Browse an Anitque Store")
RendezvousType.create(name: "Go on a Riverboat Cruise")
RendezvousType.create(name: "Go to an Amusment Park")
RendezvousType.create(name: "Have a Photoshoot")
RendezvousType.create(name: "Go on a 5k or Fun-run")
RendezvousType.create(name: "Bike Ride")
RendezvousType.create(name: "Canoe trip")
RendezvousType.create(name: "Go to a Driving Range")
RendezvousType.create(name: "Go on a Segway Tour")
RendezvousType.create(name: "Build-Your-Own-Pizza Bar")
RendezvousType.create(name: "Play Mad Libs")
RendezvousType.create(name: "Go to a Shooting Range")
RendezvousType.create(name: "Play Tennis")
RendezvousType.create(name: "Browse Downtown")
RendezvousType.create(name: "Bake Cookies Together")
RendezvousType.create(name: "Go to a Water Park")
RendezvousType.create(name: "Go to an Open Mic Night")
RendezvousType.create(name: "Go to the Craft Fair")
RendezvousType.create(name: "Take a Foreign Language Class")
RendezvousType.create(name: "Go Berry Picking")
RendezvousType.create(name: "Go to The Zoo")
RendezvousType.create(name: "Go to a Bakery")
RendezvousType.create(name: "Train Ride")
RendezvousType.create(name: "Horseback Riding")
RendezvousType.create(name: "Art Festival")
RendezvousType.create(name: "Renaissance Fair")
RendezvousType.create(name: "Ice Skating")
RendezvousType.create(name: "Go to a Play")
RendezvousType.create(name: "Go to a Cndy Making Factory")
RendezvousType.create(name: "Go to a Food Festival")
RendezvousType.create(name: "Have a Barbecue")
RendezvousType.create(name: "Host a Dinner Party")
RendezvousType.create(name: "Make Ice Cream")
RendezvousType.create(name: "Go to Wildlife Reserve")
RendezvousType.create(name: "Go to a Science Center")
RendezvousType.create(name: "Go to a Ballet")
RendezvousType.create(name: "Go to the Circus")
RendezvousType.create(name: "Go to an Escape Room")
RendezvousType.create(name: "Make a Scrape Book")
RendezvousType.create(name: "Go watch Sports Game")
RendezvousType.create(name: "Go to Aquarium")
RendezvousType.create(name: "Trivia Night at Local Bar")
RendezvousType.create(name: "Visit Scenic Point")
RendezvousType.create(name: "Visit New Town")
RendezvousType.create(name: "Get Tattoes together")
RendezvousType.create(name: "Get Piercing Together")
RendezvousType.create(name: "Go Camping")
RendezvousType.create(name: "Go out on a Boat")
RendezvousType.create(name: "Go to the Beach")
RendezvousType.create(name: "Netflix and Chill")
RendezvousType.create(name: "Redo a Room")
RendezvousType.create(name: "Visit Farmers Market")
RendezvousType.create(name: "Jazz Club")
RendezvousType.create(name: "Take a Dance Class")
RendezvousType.create(name: "Go Dancing")
RendezvousType.create(name: "Play Pool")
RendezvousType.create(name: "Weekend Trip")
RendezvousType.create(name: "Go have Brunch")
RendezvousType.create(name: "Birdwatching")
RendezvousType.create(name: "Take Improv Class")
RendezvousType.create(name: "Brewery Tour")
RendezvousType.create(name: "Winery Tour")
RendezvousType.create(name: "Go to a Drive-in")
RendezvousType.create(name: "Brew your own Beer together")
RendezvousType.create(name: "Go to the Club")
RendezvousType.create(name: "Bungie Jumping")
RendezvousType.create(name: "Sky Diving")
RendezvousType.create(name: "Wiskey Tasting")
RendezvousType.create(name: "Mud Run/ Color Run")
RendezvousType.create(name: "Spa Day")
RendezvousType.create(name: "Go to a Open House")
RendezvousType.create(name: "Rock Climbing")
RendezvousType.create(name: "Snowboarding/ Ski trip")
RendezvousType.create(name: "Go to a Five Star Restraunt")
RendezvousType.create(name: "Visit a Local Restraunt")
RendezvousType.create(name: "Go to a Zipline")
